import { mkdirSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

const RULE_SOURCE = `'use strict';

/**
 * Forbids raw string-literal className values (the Tailwind/shadcn "utility
 * soup" pattern). Customization must flow through a component's variant
 * props or a recipe function call instead — any expression that isn't a
 * bare string literal is allowed. Generated by forgekit-reactor.
 */
module.exports = {
  meta: {
    type: 'problem',
    docs: {
      description:
        'Disallow raw string-literal className values; use component variants or a recipe function instead.',
    },
    schema: [],
    messages: {
      rawClassname:
        "Raw className string literals are forbidden here. Use the component's variant props, or a recipe function call, instead of inline utility classes.",
    },
  },
  create(context) {
    return {
      JSXAttribute(node) {
        if (node.name?.type !== 'JSXIdentifier' || node.name.name !== 'className') {
          return;
        }
        const value = node.value;
        if (!value) return;
        const isBareStringLiteral =
          (value.type === 'Literal' && typeof value.value === 'string') ||
          (value.type === 'JSXExpressionContainer' &&
            value.expression?.type === 'Literal' &&
            typeof value.expression.value === 'string') ||
          (value.type === 'JSXExpressionContainer' &&
            value.expression?.type === 'TemplateLiteral' &&
            value.expression.expressions.length === 0);
        if (isBareStringLiteral) {
          context.report({ node, messageId: 'rawClassname' });
        }
      },
    };
  },
};
`;

const LOCAL_ESLINT_CONFIG = `import localRules from './.eslint-rules/no-raw-classname.cjs';

/** Local ESLint flat config enforcing no-raw-classname under this lib. Generated by forgekit-reactor. */
export default [
  {
    files: ['src/**/*.{jsx,tsx}'],
    languageOptions: { parserOptions: { ecmaFeatures: { jsx: true } } },
    plugins: { local: { rules: { 'no-raw-classname': localRules } } },
    rules: { 'local/no-raw-classname': 'error' },
  },
];
`;

export function emitNoRawClassnameRuleFile(uiLibDir: string): void {
  const ruleDir = join(uiLibDir, '.eslint-rules');
  mkdirSync(ruleDir, { recursive: true });
  writeFileSync(join(ruleDir, 'no-raw-classname.cjs'), RULE_SOURCE);
  writeFileSync(join(uiLibDir, 'eslint.config.local.mjs'), LOCAL_ESLINT_CONFIG);
}
